# Generated by Django 4.2.29 on 2026-03-30 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_property_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='property',
            new_name='properties_city_c34f4f_idx',
            old_name='listings_pr_city_19bdd1_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='properties_status_e6008a_idx',
            old_name='listings_pr_status_de90a3_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='properties_propert_f38ecc_idx',
            old_name='listings_pr_propert_36edbb_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='properties_created_2ede73_idx',
            old_name='listings_pr_created_e6aabb_idx',
        ),
        migrations.AlterModelTable(
            name='property',
            table='properties',
        ),
        migrations.AlterModelTable(
            name='propertyimage',
            table='property_images',
        ),
    ]
