# Generated by Django 4.2.29 on 2026-03-30 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_remove_contactmessage_messaging_c_deleted_338054_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contactmessage',
            name='messaging_c_is_read_800166_idx',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_read',
        ),
    ]
