# Generated by Django 4.2.29 on 2026-03-30 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_remove_contactmessage_messaging_c_is_read_800166_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contactmessage',
            new_name='contact_mes_created_684d0e_idx',
            old_name='messaging_c_created_0b4cd8_idx',
        ),
        migrations.RenameIndex(
            model_name='inquiry',
            new_name='inquiries_to_user_a91734_idx',
            old_name='messaging_i_to_user_c6efc8_idx',
        ),
        migrations.RenameIndex(
            model_name='inquiry',
            new_name='inquiries_to_user_27f706_idx',
            old_name='messaging_i_to_user_8c8e19_idx',
        ),
        migrations.RenameIndex(
            model_name='inquiry',
            new_name='inquiries_created_e30e4f_idx',
            old_name='messaging_i_created_1d9354_idx',
        ),
        migrations.RenameIndex(
            model_name='inquirymessage',
            new_name='inquiry_mes_inquiry_2f1784_idx',
            old_name='messaging_i_inquiry_6705dc_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='reservation_house_i_e8c5bb_idx',
            old_name='messaging_r_house_i_5d257a_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='reservation_to_user_492e93_idx',
            old_name='messaging_r_to_user_f593f3_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='reservation_to_user_fc1dd2_idx',
            old_name='messaging_r_to_user_dd04bc_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='reservation_created_e245c6_idx',
            old_name='messaging_r_created_0dabcd_idx',
        ),
        migrations.AlterModelTable(
            name='contactmessage',
            table='contact_messages',
        ),
        migrations.AlterModelTable(
            name='inquiry',
            table='inquiries',
        ),
        migrations.AlterModelTable(
            name='inquirymessage',
            table='inquiry_messages',
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='reservations',
        ),
    ]
